image: node:14-alpine

stages:
    - npm-publish
    - github-publish

npm-publish:
    stage: npm-publish
    tags:
        - docker
    when: manual
    script:
        - npm install
        - npm init --scope=@meddream
        - echo "//registry.npmjs.org/:_authToken=$NPM_REG_TOKEN" > $CI_PROJECT_DIR/.npmrc
        - npm publish --access public

github-publish:
    stage: github-publish
    tags:
        - docker
    when: manual
    script:
        - apk add --update --no-cache git
